import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/space-icon.ico" />
      </Head>
      <section className="w-11/12 m-auto flex justify-between items-center">
        <Link href="/">
          <a>
            <Image
              src="/images/space-logo.svg"
              alt="space logo"
              width={70}
              height={70}
              className="cursor-pointer"
            />
          </a>
        </Link>

        <div className="font-poppins text-lightGrey font-extralight">
          <p>En</p>
        </div>
      </section>
      <section className="font-poppins text-lightGrey">{children}</section>
    </>
  );
}
